-- DB name: "University"
-- CREATE DATABASE University;

CREATE schema public;

-- === PROFESSORS TABLE ===

CREATE TABLE public.professors (
    professor_id SERIAL PRIMARY KEY,
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL
);

ALTER TABLE public.professors OWNER TO postgres;

insert into public.professors (firstname, lastname) values ('Ailee', 'Daw');
insert into public.professors (firstname, lastname) values ('Jerri', 'Vacher');
insert into public.professors (firstname, lastname) values ('Alvy', 'Leborgne');
insert into public.professors (firstname, lastname) values ('Archibald', 'Haselgrove');
insert into public.professors (firstname, lastname) values ('Horatia', 'Nind');
insert into public.professors (firstname, lastname) values ('Janos', 'Lytle');
insert into public.professors (firstname, lastname) values ('Martie', 'Happel');
insert into public.professors (firstname, lastname) values ('Carley', 'Hargess');
insert into public.professors (firstname, lastname) values ('Shauna', 'Harmson');
insert into public.professors (firstname, lastname) values ('Mitchell', 'Colchett');
insert into public.professors (firstname, lastname) values ('Maybelle', 'Favelle');
insert into public.professors (firstname, lastname) values ('Florian', 'Keneleyside');
insert into public.professors (firstname, lastname) values ('Daveen', 'Jellings');
insert into public.professors (firstname, lastname) values ('Trstram', 'Hamlet');
insert into public.professors (firstname, lastname) values ('Evy', 'Stillgoe');
insert into public.professors (firstname, lastname) values ('Tammie', 'Sinkins');
insert into public.professors (firstname, lastname) values ('Lucita', 'Grieg');
insert into public.professors (firstname, lastname) values ('Emmerich', 'Bezant');
insert into public.professors (firstname, lastname) values ('Ware', 'Tarply');
insert into public.professors (firstname, lastname) values ('Taber', 'Simonetto');
insert into public.professors (firstname, lastname) values ('Allister', 'Pattisson');
insert into public.professors (firstname, lastname) values ('Merwin', 'Bloan');
insert into public.professors (firstname, lastname) values ('Layton', 'Allnutt');
insert into public.professors (firstname, lastname) values ('Emory', 'Pocknell');
insert into public.professors (firstname, lastname) values ('Maria', 'Jamrowicz');

-- === STUDENTS TABLE ===

CREATE TABLE public.students (
    student_id SERIAL PRIMARY KEY,
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL
);

ALTER TABLE public.students OWNER TO postgres;

insert into public.students (firstname, lastname) values ('Sela', 'Gaitskell');
insert into public.students (firstname, lastname) values ('Lebbie', 'Rihosek');
insert into public.students (firstname, lastname) values ('Joana', 'Skelcher');
insert into public.students (firstname, lastname) values ('Mahala', 'Cowope');
insert into public.students (firstname, lastname) values ('Golda', 'Reeme');
insert into public.students (firstname, lastname) values ('Lester', 'Butts');
insert into public.students (firstname, lastname) values ('Belvia', 'O''Lagen');
insert into public.students (firstname, lastname) values ('Jo-anne', 'Gronaller');
insert into public.students (firstname, lastname) values ('Laney', 'Steere');
insert into public.students (firstname, lastname) values ('Robinson', 'Chomley');
insert into public.students (firstname, lastname) values ('Balduin', 'Millins');
insert into public.students (firstname, lastname) values ('Anthiathia', 'Abrashkov');
insert into public.students (firstname, lastname) values ('Joye', 'Measor');
insert into public.students (firstname, lastname) values ('Prudy', 'Peiser');
insert into public.students (firstname, lastname) values ('Tonie', 'McKaile');
insert into public.students (firstname, lastname) values ('Muhammad', 'Goddert.sf');
insert into public.students (firstname, lastname) values ('Wain', 'MacAscaidh');
insert into public.students (firstname, lastname) values ('Florrie', 'Greenaway');
insert into public.students (firstname, lastname) values ('Rea', 'Boler');
insert into public.students (firstname, lastname) values ('Jinny', 'Paraman');
insert into public.students (firstname, lastname) values ('Orelee', 'Davydoch');
insert into public.students (firstname, lastname) values ('Alexandros', 'Cadigan');
insert into public.students (firstname, lastname) values ('Dania', 'Bowgen');
insert into public.students (firstname, lastname) values ('Melessa', 'Dorling');
insert into public.students (firstname, lastname) values ('Hugibert', 'Gilliland');
insert into public.students (firstname, lastname) values ('Artie', 'Paskins');
insert into public.students (firstname, lastname) values ('Winona', 'Godball');
insert into public.students (firstname, lastname) values ('Auria', 'Mocher');
insert into public.students (firstname, lastname) values ('Grant', 'Jervis');
insert into public.students (firstname, lastname) values ('Evangelia', 'Oglesbee');
insert into public.students (firstname, lastname) values ('Quinton', 'Haggie');
insert into public.students (firstname, lastname) values ('Tyrone', 'Lermit');
insert into public.students (firstname, lastname) values ('Wayne', 'Buxcey');
insert into public.students (firstname, lastname) values ('Modestia', 'Olyfant');
insert into public.students (firstname, lastname) values ('Rudolfo', 'Hargreaves');
insert into public.students (firstname, lastname) values ('Dinnie', 'Phripp');
insert into public.students (firstname, lastname) values ('Noach', 'Selway');
insert into public.students (firstname, lastname) values ('Berte', 'Ollerhead');
insert into public.students (firstname, lastname) values ('Gerrie', 'Surgenor');
insert into public.students (firstname, lastname) values ('Augustine', 'Ruperti');
insert into public.students (firstname, lastname) values ('Alyse', 'Playfoot');
insert into public.students (firstname, lastname) values ('Rhona', 'Pairpoint');
insert into public.students (firstname, lastname) values ('Coleen', 'Garric');
insert into public.students (firstname, lastname) values ('Neille', 'Bickerdicke');
insert into public.students (firstname, lastname) values ('Peyton', 'Drane');
insert into public.students (firstname, lastname) values ('Devy', 'Capelin');
insert into public.students (firstname, lastname) values ('Raphael', 'Dundon');
insert into public.students (firstname, lastname) values ('Brandi', 'Toop');
insert into public.students (firstname, lastname) values ('Ring', 'Peskett');
insert into public.students (firstname, lastname) values ('Maiga', 'Nestoruk');
insert into public.students (firstname, lastname) values ('El', 'Ilyin');
insert into public.students (firstname, lastname) values ('Job', 'Huckett');
insert into public.students (firstname, lastname) values ('Dorris', 'Christiensen');
insert into public.students (firstname, lastname) values ('Rodina', 'Glasson');
insert into public.students (firstname, lastname) values ('Edee', 'Benoist');
insert into public.students (firstname, lastname) values ('Bradly', 'Kidston');
insert into public.students (firstname, lastname) values ('Arne', 'Ben');
insert into public.students (firstname, lastname) values ('Tore', 'Revie');
insert into public.students (firstname, lastname) values ('Lyndel', 'Brandrick');
insert into public.students (firstname, lastname) values ('Joellyn', 'Lapides');
insert into public.students (firstname, lastname) values ('Rochelle', 'Bonn');
insert into public.students (firstname, lastname) values ('Kassey', 'Fotherby');
insert into public.students (firstname, lastname) values ('Ira', 'Roose');
insert into public.students (firstname, lastname) values ('Rodge', 'Piers');
insert into public.students (firstname, lastname) values ('Nona', 'Hubach');
insert into public.students (firstname, lastname) values ('Benjamen', 'Dettmar');
insert into public.students (firstname, lastname) values ('Farrel', 'Filyaev');
insert into public.students (firstname, lastname) values ('Dimitri', 'O''Criane');
insert into public.students (firstname, lastname) values ('Waring', 'Chastenet');
insert into public.students (firstname, lastname) values ('Abra', 'Tesseyman');
insert into public.students (firstname, lastname) values ('Clotilda', 'Broose');
insert into public.students (firstname, lastname) values ('Mateo', 'Speke');
insert into public.students (firstname, lastname) values ('Earlie', 'Halliday');
insert into public.students (firstname, lastname) values ('Louisa', 'Dauney');
insert into public.students (firstname, lastname) values ('Susanne', 'Chaddock');
insert into public.students (firstname, lastname) values ('Saloma', 'Ferraretto');
insert into public.students (firstname, lastname) values ('Sloan', 'Dallison');
insert into public.students (firstname, lastname) values ('Lexis', 'Fain');
insert into public.students (firstname, lastname) values ('Brigham', 'Kingett');
insert into public.students (firstname, lastname) values ('Trudie', 'Paliser');
insert into public.students (firstname, lastname) values ('Olympie', 'Tejada');
insert into public.students (firstname, lastname) values ('Silvan', 'Rayworth');
insert into public.students (firstname, lastname) values ('Kirsti', 'Kybird');
insert into public.students (firstname, lastname) values ('Catlin', 'Doerr');
insert into public.students (firstname, lastname) values ('Yasmin', 'Petrescu');
insert into public.students (firstname, lastname) values ('Marja', 'Joannic');
insert into public.students (firstname, lastname) values ('Celia', 'Conrart');
insert into public.students (firstname, lastname) values ('Romola', 'Rouse');
insert into public.students (firstname, lastname) values ('Terese', 'Shaddick');
insert into public.students (firstname, lastname) values ('Monah', 'Darley');
insert into public.students (firstname, lastname) values ('Rochelle', 'Vanin');
insert into public.students (firstname, lastname) values ('Ludovico', 'Payfoot');
insert into public.students (firstname, lastname) values ('Diarmid', 'Combe');
insert into public.students (firstname, lastname) values ('Berti', 'Haine');
insert into public.students (firstname, lastname) values ('Garrott', 'Garrow');
insert into public.students (firstname, lastname) values ('Bernette', 'Blinkhorn');
insert into public.students (firstname, lastname) values ('Rooney', 'Jaime');
insert into public.students (firstname, lastname) values ('Katy', 'Michie');
insert into public.students (firstname, lastname) values ('Terrell', 'Luxmoore');
insert into public.students (firstname, lastname) values ('Giuseppe', 'Ledgley');

-- -- === COURSE SUBJECTS TABLE ===

CREATE TABLE public."course_subject" (
    subject_id SERIAL PRIMARY KEY,
    course_subject character varying(50) NOT NULL
);

ALTER TABLE public."course_subject" OWNER TO postgres;

INSERT INTO public."course_subject" (course_subject) VALUES
('History'),
('Math'),
('Law'),
('English'),
('Programming');

-- -- === COURSES TABLE ===

CREATE TABLE public.courses (
    course_id SERIAL PRIMARY KEY,
    professor_id integer,
    subject_id integer,
    constraint fk_courses_professors
      foreign key (professor_id)
      REFERENCES public.professors (professor_id),
    constraint fk_courses_subject
      foreign key (subject_id)
      REFERENCES public."course_subject" (subject_id)
);

ALTER TABLE public.courses OWNER TO postgres;

insert into public.courses (professor_id, subject_id) values (25, 5);
insert into public.courses (professor_id, subject_id) values (21, 1);
insert into public.courses (professor_id, subject_id) values (14, 2);
insert into public.courses (professor_id, subject_id) values (3, 4);
insert into public.courses (professor_id, subject_id) values (17, 1);
insert into public.courses (professor_id, subject_id) values (17, 4);
insert into public.courses (professor_id, subject_id) values (11, 4);
insert into public.courses (professor_id, subject_id) values (15, 2);
insert into public.courses (professor_id, subject_id) values (12, 4);
insert into public.courses (professor_id, subject_id) values (5, 4);
insert into public.courses (professor_id, subject_id) values (13, 3);
insert into public.courses (professor_id, subject_id) values (17, 3);
insert into public.courses (professor_id, subject_id) values (17, 4);
insert into public.courses (professor_id, subject_id) values (7, 5);
insert into public.courses (professor_id, subject_id) values (19, 4);
insert into public.courses (professor_id, subject_id) values (6, 3);
insert into public.courses (professor_id, subject_id) values (13, 5);
insert into public.courses (professor_id, subject_id) values (23, 5);
insert into public.courses (professor_id, subject_id) values (4, 1);
insert into public.courses (professor_id, subject_id) values (11, 3);
insert into public.courses (professor_id, subject_id) values (22, 5);
insert into public.courses (professor_id, subject_id) values (20, 2);
insert into public.courses (professor_id, subject_id) values (16, 2);
insert into public.courses (professor_id, subject_id) values (9, 5);
insert into public.courses (professor_id, subject_id) values (21, 4);
insert into public.courses (professor_id, subject_id) values (1, 3);
insert into public.courses (professor_id, subject_id) values (14, 2);
insert into public.courses (professor_id, subject_id) values (25, 2);
insert into public.courses (professor_id, subject_id) values (4, 2);
insert into public.courses (professor_id, subject_id) values (10, 2);
insert into public.courses (professor_id, subject_id) values (15, 3);
insert into public.courses (professor_id, subject_id) values (20, 2);
insert into public.courses (professor_id, subject_id) values (4, 4);
insert into public.courses (professor_id, subject_id) values (10, 4);
insert into public.courses (professor_id, subject_id) values (7, 5);
insert into public.courses (professor_id, subject_id) values (22, 1);
insert into public.courses (professor_id, subject_id) values (20, 2);
insert into public.courses (professor_id, subject_id) values (1, 3);
insert into public.courses (professor_id, subject_id) values (20, 1);
insert into public.courses (professor_id, subject_id) values (18, 5);
insert into public.courses (professor_id, subject_id) values (6, 2);
insert into public.courses (professor_id, subject_id) values (17, 3);
insert into public.courses (professor_id, subject_id) values (25, 1);
insert into public.courses (professor_id, subject_id) values (11, 5);
insert into public.courses (professor_id, subject_id) values (8, 4);
insert into public.courses (professor_id, subject_id) values (12, 5);
insert into public.courses (professor_id, subject_id) values (5, 2);
insert into public.courses (professor_id, subject_id) values (12, 3);
insert into public.courses (professor_id, subject_id) values (1, 2);
insert into public.courses (professor_id, subject_id) values (14, 3);

-- -- === RESULTS TABLE ===

CREATE TABLE public.results (
    student_id integer,
    course_id integer,
    result integer NOT NULL,
    constraint fk_results_students
      foreign key (student_id)
      REFERENCES public.students (student_id),
    constraint fk_results_courses
      foreign key (course_id)
      REFERENCES public.courses (course_id)
);

ALTER TABLE public.results OWNER TO postgres;

insert into public.results (student_id, course_id, result) values (36, 13, 3);
insert into public.results (student_id, course_id, result) values (80, 44, 2);
insert into public.results (student_id, course_id, result) values (25, 1, 17);
insert into public.results (student_id, course_id, result) values (55, 24, 1);
insert into public.results (student_id, course_id, result) values (8, 4, 14);
insert into public.results (student_id, course_id, result) values (58, 50, 7);
insert into public.results (student_id, course_id, result) values (100, 2, 16);
insert into public.results (student_id, course_id, result) values (35, 11, 15);
insert into public.results (student_id, course_id, result) values (80, 36, 4);
insert into public.results (student_id, course_id, result) values (67, 12, 6);
insert into public.results (student_id, course_id, result) values (53, 34, 5);
insert into public.results (student_id, course_id, result) values (19, 4, 7);
insert into public.results (student_id, course_id, result) values (55, 49, 9);
insert into public.results (student_id, course_id, result) values (52, 32, 5);
insert into public.results (student_id, course_id, result) values (14, 29, 13);
insert into public.results (student_id, course_id, result) values (55, 48, 13);
insert into public.results (student_id, course_id, result) values (43, 25, 20);
insert into public.results (student_id, course_id, result) values (74, 27, 18);
insert into public.results (student_id, course_id, result) values (53, 27, 14);
insert into public.results (student_id, course_id, result) values (85, 40, 8);
insert into public.results (student_id, course_id, result) values (49, 45, 5);
insert into public.results (student_id, course_id, result) values (64, 17, 4);
insert into public.results (student_id, course_id, result) values (24, 25, 9);
insert into public.results (student_id, course_id, result) values (84, 9, 6);
insert into public.results (student_id, course_id, result) values (33, 40, 8);
insert into public.results (student_id, course_id, result) values (32, 10, 9);
insert into public.results (student_id, course_id, result) values (88, 10, 7);
insert into public.results (student_id, course_id, result) values (42, 48, 1);
insert into public.results (student_id, course_id, result) values (66, 40, 10);
insert into public.results (student_id, course_id, result) values (7, 36, 1);
insert into public.results (student_id, course_id, result) values (22, 28, 3);
insert into public.results (student_id, course_id, result) values (51, 40, 4);
insert into public.results (student_id, course_id, result) values (4, 23, 12);
insert into public.results (student_id, course_id, result) values (85, 29, 1);
insert into public.results (student_id, course_id, result) values (66, 19, 4);
insert into public.results (student_id, course_id, result) values (22, 45, 5);
insert into public.results (student_id, course_id, result) values (16, 26, 1);
insert into public.results (student_id, course_id, result) values (48, 48, 8);
insert into public.results (student_id, course_id, result) values (96, 36, 3);
insert into public.results (student_id, course_id, result) values (94, 20, 20);
insert into public.results (student_id, course_id, result) values (73, 30, 2);
insert into public.results (student_id, course_id, result) values (87, 30, 15);
insert into public.results (student_id, course_id, result) values (47, 1, 17);
insert into public.results (student_id, course_id, result) values (17, 29, 3);
insert into public.results (student_id, course_id, result) values (69, 23, 12);
insert into public.results (student_id, course_id, result) values (9, 2, 1);
insert into public.results (student_id, course_id, result) values (77, 40, 9);
insert into public.results (student_id, course_id, result) values (19, 3, 5);
insert into public.results (student_id, course_id, result) values (78, 31, 2);
insert into public.results (student_id, course_id, result) values (80, 50, 19);
insert into public.results (student_id, course_id, result) values (38, 27, 19);
insert into public.results (student_id, course_id, result) values (44, 26, 2);
insert into public.results (student_id, course_id, result) values (39, 13, 17);
insert into public.results (student_id, course_id, result) values (60, 37, 8);
insert into public.results (student_id, course_id, result) values (21, 49, 8);
insert into public.results (student_id, course_id, result) values (22, 12, 5);
insert into public.results (student_id, course_id, result) values (34, 31, 2);
insert into public.results (student_id, course_id, result) values (5, 7, 14);
insert into public.results (student_id, course_id, result) values (99, 34, 15);
insert into public.results (student_id, course_id, result) values (58, 8, 16);
insert into public.results (student_id, course_id, result) values (54, 36, 6);
insert into public.results (student_id, course_id, result) values (65, 15, 9);
insert into public.results (student_id, course_id, result) values (13, 48, 3);
insert into public.results (student_id, course_id, result) values (10, 28, 8);
insert into public.results (student_id, course_id, result) values (38, 41, 1);
insert into public.results (student_id, course_id, result) values (45, 29, 20);
insert into public.results (student_id, course_id, result) values (60, 21, 17);
insert into public.results (student_id, course_id, result) values (23, 7, 18);
insert into public.results (student_id, course_id, result) values (35, 3, 7);
insert into public.results (student_id, course_id, result) values (9, 8, 11);
insert into public.results (student_id, course_id, result) values (77, 12, 6);
insert into public.results (student_id, course_id, result) values (68, 12, 12);
insert into public.results (student_id, course_id, result) values (19, 31, 11);
insert into public.results (student_id, course_id, result) values (28, 44, 3);
insert into public.results (student_id, course_id, result) values (77, 35, 20);
insert into public.results (student_id, course_id, result) values (48, 12, 19);
insert into public.results (student_id, course_id, result) values (24, 39, 6);
insert into public.results (student_id, course_id, result) values (45, 34, 11);
insert into public.results (student_id, course_id, result) values (46, 37, 6);
insert into public.results (student_id, course_id, result) values (77, 27, 19);
insert into public.results (student_id, course_id, result) values (25, 6, 3);
insert into public.results (student_id, course_id, result) values (58, 29, 1);
insert into public.results (student_id, course_id, result) values (34, 41, 9);
insert into public.results (student_id, course_id, result) values (93, 45, 12);
insert into public.results (student_id, course_id, result) values (67, 36, 5);
insert into public.results (student_id, course_id, result) values (96, 14, 5);
insert into public.results (student_id, course_id, result) values (67, 13, 18);
insert into public.results (student_id, course_id, result) values (32, 31, 4);
insert into public.results (student_id, course_id, result) values (88, 21, 8);
insert into public.results (student_id, course_id, result) values (26, 44, 12);
insert into public.results (student_id, course_id, result) values (86, 48, 17);
insert into public.results (student_id, course_id, result) values (6, 33, 5);
insert into public.results (student_id, course_id, result) values (98, 37, 19);
insert into public.results (student_id, course_id, result) values (25, 17, 12);
insert into public.results (student_id, course_id, result) values (25, 45, 5);
insert into public.results (student_id, course_id, result) values (22, 18, 2);
insert into public.results (student_id, course_id, result) values (47, 21, 15);
insert into public.results (student_id, course_id, result) values (2, 24, 1);
insert into public.results (student_id, course_id, result) values (34, 46, 10);
insert into public.results (student_id, course_id, result) values (14, 48, 18);
insert into public.results (student_id, course_id, result) values (100, 47, 9);
insert into public.results (student_id, course_id, result) values (85, 49, 17);
insert into public.results (student_id, course_id, result) values (63, 21, 7);
insert into public.results (student_id, course_id, result) values (56, 45, 17);
insert into public.results (student_id, course_id, result) values (68, 5, 10);
insert into public.results (student_id, course_id, result) values (85, 19, 16);
insert into public.results (student_id, course_id, result) values (25, 28, 12);
insert into public.results (student_id, course_id, result) values (88, 26, 18);
insert into public.results (student_id, course_id, result) values (27, 27, 4);
insert into public.results (student_id, course_id, result) values (32, 3, 17);
insert into public.results (student_id, course_id, result) values (74, 50, 1);
insert into public.results (student_id, course_id, result) values (73, 16, 11);
insert into public.results (student_id, course_id, result) values (60, 1, 7);
insert into public.results (student_id, course_id, result) values (75, 18, 20);
insert into public.results (student_id, course_id, result) values (24, 18, 19);
insert into public.results (student_id, course_id, result) values (62, 22, 12);
insert into public.results (student_id, course_id, result) values (69, 1, 4);
insert into public.results (student_id, course_id, result) values (98, 47, 3);
insert into public.results (student_id, course_id, result) values (54, 11, 13);
insert into public.results (student_id, course_id, result) values (65, 10, 7);
insert into public.results (student_id, course_id, result) values (77, 34, 8);
insert into public.results (student_id, course_id, result) values (21, 14, 16);
insert into public.results (student_id, course_id, result) values (13, 25, 12);
insert into public.results (student_id, course_id, result) values (64, 4, 13);
insert into public.results (student_id, course_id, result) values (70, 23, 13);
insert into public.results (student_id, course_id, result) values (74, 45, 17);
insert into public.results (student_id, course_id, result) values (41, 42, 17);
insert into public.results (student_id, course_id, result) values (57, 35, 14);
insert into public.results (student_id, course_id, result) values (78, 48, 4);
insert into public.results (student_id, course_id, result) values (71, 20, 6);
insert into public.results (student_id, course_id, result) values (65, 27, 16);
insert into public.results (student_id, course_id, result) values (32, 30, 6);
insert into public.results (student_id, course_id, result) values (80, 3, 19);
insert into public.results (student_id, course_id, result) values (53, 21, 5);
insert into public.results (student_id, course_id, result) values (89, 13, 7);
insert into public.results (student_id, course_id, result) values (96, 22, 17);
insert into public.results (student_id, course_id, result) values (49, 29, 15);
insert into public.results (student_id, course_id, result) values (20, 12, 9);
insert into public.results (student_id, course_id, result) values (81, 22, 4);
insert into public.results (student_id, course_id, result) values (63, 41, 4);
insert into public.results (student_id, course_id, result) values (36, 50, 14);
insert into public.results (student_id, course_id, result) values (67, 1, 12);
insert into public.results (student_id, course_id, result) values (64, 40, 1);
insert into public.results (student_id, course_id, result) values (91, 22, 2);
insert into public.results (student_id, course_id, result) values (9, 23, 1);
insert into public.results (student_id, course_id, result) values (86, 17, 14);
insert into public.results (student_id, course_id, result) values (61, 48, 20);
insert into public.results (student_id, course_id, result) values (12, 28, 19);
insert into public.results (student_id, course_id, result) values (76, 46, 12);
insert into public.results (student_id, course_id, result) values (61, 11, 9);
insert into public.results (student_id, course_id, result) values (15, 1, 2);
insert into public.results (student_id, course_id, result) values (100, 13, 13);
insert into public.results (student_id, course_id, result) values (94, 48, 15);
insert into public.results (student_id, course_id, result) values (30, 26, 16);
insert into public.results (student_id, course_id, result) values (40, 2, 6);
insert into public.results (student_id, course_id, result) values (60, 30, 19);
insert into public.results (student_id, course_id, result) values (32, 47, 1);
insert into public.results (student_id, course_id, result) values (96, 12, 12);
insert into public.results (student_id, course_id, result) values (6, 21, 18);
insert into public.results (student_id, course_id, result) values (81, 24, 16);
insert into public.results (student_id, course_id, result) values (14, 35, 11);
insert into public.results (student_id, course_id, result) values (72, 13, 17);
insert into public.results (student_id, course_id, result) values (18, 39, 4);
insert into public.results (student_id, course_id, result) values (18, 35, 15);
insert into public.results (student_id, course_id, result) values (19, 20, 9);
insert into public.results (student_id, course_id, result) values (33, 5, 19);
insert into public.results (student_id, course_id, result) values (84, 32, 3);
insert into public.results (student_id, course_id, result) values (74, 24, 15);
insert into public.results (student_id, course_id, result) values (74, 2, 8);
insert into public.results (student_id, course_id, result) values (43, 47, 20);
insert into public.results (student_id, course_id, result) values (18, 37, 19);
insert into public.results (student_id, course_id, result) values (69, 32, 1);
insert into public.results (student_id, course_id, result) values (65, 32, 6);
insert into public.results (student_id, course_id, result) values (72, 50, 19);
insert into public.results (student_id, course_id, result) values (13, 50, 1);
insert into public.results (student_id, course_id, result) values (35, 31, 1);
insert into public.results (student_id, course_id, result) values (4, 34, 19);
insert into public.results (student_id, course_id, result) values (55, 14, 4);
insert into public.results (student_id, course_id, result) values (79, 33, 2);
insert into public.results (student_id, course_id, result) values (20, 43, 20);
insert into public.results (student_id, course_id, result) values (47, 30, 3);
insert into public.results (student_id, course_id, result) values (46, 3, 2);
insert into public.results (student_id, course_id, result) values (64, 11, 12);
insert into public.results (student_id, course_id, result) values (43, 29, 2);
insert into public.results (student_id, course_id, result) values (31, 36, 19);
insert into public.results (student_id, course_id, result) values (19, 36, 13);
insert into public.results (student_id, course_id, result) values (13, 9, 8);
insert into public.results (student_id, course_id, result) values (19, 25, 17);
insert into public.results (student_id, course_id, result) values (96, 37, 10);
insert into public.results (student_id, course_id, result) values (18, 36, 8);
insert into public.results (student_id, course_id, result) values (79, 4, 5);
insert into public.results (student_id, course_id, result) values (42, 5, 5);
insert into public.results (student_id, course_id, result) values (27, 32, 16);
insert into public.results (student_id, course_id, result) values (47, 43, 15);
insert into public.results (student_id, course_id, result) values (86, 20, 20);
insert into public.results (student_id, course_id, result) values (68, 15, 14);
insert into public.results (student_id, course_id, result) values (46, 18, 20);
insert into public.results (student_id, course_id, result) values (37, 22, 3);
insert into public.results (student_id, course_id, result) values (1, 26, 9);
insert into public.results (student_id, course_id, result) values (100, 4, 8);
insert into public.results (student_id, course_id, result) values (44, 1, 17);
insert into public.results (student_id, course_id, result) values (31, 48, 2);
insert into public.results (student_id, course_id, result) values (11, 5, 3);
insert into public.results (student_id, course_id, result) values (35, 35, 17);
insert into public.results (student_id, course_id, result) values (73, 48, 7);
insert into public.results (student_id, course_id, result) values (8, 19, 20);
insert into public.results (student_id, course_id, result) values (90, 23, 6);
insert into public.results (student_id, course_id, result) values (80, 20, 17);
insert into public.results (student_id, course_id, result) values (19, 2, 11);
insert into public.results (student_id, course_id, result) values (93, 4, 19);
insert into public.results (student_id, course_id, result) values (28, 5, 20);
insert into public.results (student_id, course_id, result) values (1, 21, 6);
insert into public.results (student_id, course_id, result) values (82, 46, 2);
insert into public.results (student_id, course_id, result) values (55, 41, 5);
insert into public.results (student_id, course_id, result) values (95, 9, 9);
insert into public.results (student_id, course_id, result) values (27, 1, 20);
insert into public.results (student_id, course_id, result) values (88, 10, 15);
insert into public.results (student_id, course_id, result) values (48, 26, 10);
insert into public.results (student_id, course_id, result) values (66, 31, 13);
insert into public.results (student_id, course_id, result) values (54, 19, 13);
insert into public.results (student_id, course_id, result) values (28, 37, 12);
insert into public.results (student_id, course_id, result) values (50, 45, 6);
insert into public.results (student_id, course_id, result) values (30, 18, 15);
insert into public.results (student_id, course_id, result) values (35, 43, 19);
insert into public.results (student_id, course_id, result) values (62, 35, 19);
insert into public.results (student_id, course_id, result) values (8, 40, 14);
insert into public.results (student_id, course_id, result) values (48, 32, 9);
insert into public.results (student_id, course_id, result) values (80, 25, 6);
insert into public.results (student_id, course_id, result) values (26, 46, 3);
insert into public.results (student_id, course_id, result) values (40, 37, 14);
insert into public.results (student_id, course_id, result) values (14, 10, 12);
insert into public.results (student_id, course_id, result) values (42, 35, 1);
insert into public.results (student_id, course_id, result) values (100, 32, 14);
insert into public.results (student_id, course_id, result) values (28, 26, 18);
insert into public.results (student_id, course_id, result) values (43, 31, 2);
insert into public.results (student_id, course_id, result) values (87, 33, 14);
insert into public.results (student_id, course_id, result) values (61, 41, 13);
insert into public.results (student_id, course_id, result) values (40, 30, 3);
insert into public.results (student_id, course_id, result) values (1, 19, 1);
insert into public.results (student_id, course_id, result) values (6, 10, 13);
insert into public.results (student_id, course_id, result) values (81, 28, 4);
insert into public.results (student_id, course_id, result) values (15, 38, 12);
insert into public.results (student_id, course_id, result) values (55, 20, 5);
insert into public.results (student_id, course_id, result) values (60, 26, 13);
insert into public.results (student_id, course_id, result) values (8, 30, 18);
insert into public.results (student_id, course_id, result) values (62, 46, 11);
insert into public.results (student_id, course_id, result) values (44, 18, 7);
insert into public.results (student_id, course_id, result) values (86, 39, 4);
insert into public.results (student_id, course_id, result) values (31, 27, 8);
insert into public.results (student_id, course_id, result) values (10, 14, 5);
insert into public.results (student_id, course_id, result) values (94, 27, 9);
insert into public.results (student_id, course_id, result) values (74, 43, 6);
insert into public.results (student_id, course_id, result) values (80, 2, 14);
insert into public.results (student_id, course_id, result) values (44, 30, 9);
insert into public.results (student_id, course_id, result) values (87, 24, 19);
insert into public.results (student_id, course_id, result) values (18, 9, 5);
insert into public.results (student_id, course_id, result) values (93, 23, 13);
insert into public.results (student_id, course_id, result) values (58, 46, 20);
insert into public.results (student_id, course_id, result) values (99, 11, 13);
insert into public.results (student_id, course_id, result) values (23, 17, 17);
insert into public.results (student_id, course_id, result) values (63, 49, 7);
insert into public.results (student_id, course_id, result) values (3, 38, 13);
insert into public.results (student_id, course_id, result) values (50, 2, 14);
insert into public.results (student_id, course_id, result) values (29, 31, 5);
insert into public.results (student_id, course_id, result) values (34, 5, 1);
insert into public.results (student_id, course_id, result) values (1, 44, 7);
insert into public.results (student_id, course_id, result) values (9, 18, 3);
insert into public.results (student_id, course_id, result) values (46, 11, 20);
insert into public.results (student_id, course_id, result) values (91, 13, 15);
insert into public.results (student_id, course_id, result) values (44, 29, 14);
insert into public.results (student_id, course_id, result) values (47, 3, 8);
insert into public.results (student_id, course_id, result) values (14, 8, 3);
insert into public.results (student_id, course_id, result) values (32, 29, 11);
insert into public.results (student_id, course_id, result) values (3, 16, 16);
insert into public.results (student_id, course_id, result) values (64, 39, 15);
insert into public.results (student_id, course_id, result) values (88, 20, 10);
insert into public.results (student_id, course_id, result) values (63, 16, 4);
insert into public.results (student_id, course_id, result) values (32, 33, 17);
insert into public.results (student_id, course_id, result) values (47, 38, 20);
insert into public.results (student_id, course_id, result) values (58, 33, 20);
insert into public.results (student_id, course_id, result) values (87, 13, 2);
insert into public.results (student_id, course_id, result) values (18, 27, 19);
insert into public.results (student_id, course_id, result) values (21, 35, 4);
insert into public.results (student_id, course_id, result) values (69, 20, 6);
insert into public.results (student_id, course_id, result) values (85, 43, 12);
insert into public.results (student_id, course_id, result) values (53, 26, 8);
insert into public.results (student_id, course_id, result) values (9, 49, 5);
insert into public.results (student_id, course_id, result) values (14, 12, 8);
insert into public.results (student_id, course_id, result) values (51, 15, 7);
insert into public.results (student_id, course_id, result) values (25, 48, 5);
insert into public.results (student_id, course_id, result) values (26, 18, 19);
insert into public.results (student_id, course_id, result) values (34, 38, 18);
insert into public.results (student_id, course_id, result) values (5, 38, 6);
insert into public.results (student_id, course_id, result) values (95, 14, 11);
insert into public.results (student_id, course_id, result) values (30, 42, 6);
insert into public.results (student_id, course_id, result) values (31, 35, 19);
insert into public.results (student_id, course_id, result) values (1, 19, 1);
insert into public.results (student_id, course_id, result) values (59, 4, 1);
insert into public.results (student_id, course_id, result) values (54, 12, 8);
insert into public.results (student_id, course_id, result) values (24, 19, 6);
insert into public.results (student_id, course_id, result) values (74, 9, 15);
insert into public.results (student_id, course_id, result) values (23, 24, 7);
insert into public.results (student_id, course_id, result) values (37, 23, 12);
insert into public.results (student_id, course_id, result) values (12, 45, 2);
insert into public.results (student_id, course_id, result) values (54, 21, 14);
insert into public.results (student_id, course_id, result) values (81, 27, 14);
insert into public.results (student_id, course_id, result) values (74, 47, 10);
insert into public.results (student_id, course_id, result) values (50, 47, 11);
insert into public.results (student_id, course_id, result) values (89, 42, 18);
insert into public.results (student_id, course_id, result) values (12, 2, 7);
insert into public.results (student_id, course_id, result) values (91, 18, 2);
insert into public.results (student_id, course_id, result) values (40, 20, 4);
insert into public.results (student_id, course_id, result) values (34, 8, 9);
insert into public.results (student_id, course_id, result) values (65, 34, 19);
insert into public.results (student_id, course_id, result) values (72, 40, 10);
insert into public.results (student_id, course_id, result) values (88, 49, 7);
insert into public.results (student_id, course_id, result) values (19, 11, 11);
insert into public.results (student_id, course_id, result) values (89, 39, 12);
insert into public.results (student_id, course_id, result) values (32, 6, 3);
insert into public.results (student_id, course_id, result) values (57, 18, 7);
insert into public.results (student_id, course_id, result) values (76, 27, 8);
insert into public.results (student_id, course_id, result) values (2, 1, 20);
insert into public.results (student_id, course_id, result) values (29, 44, 6);
insert into public.results (student_id, course_id, result) values (34, 33, 12);
insert into public.results (student_id, course_id, result) values (100, 30, 9);
insert into public.results (student_id, course_id, result) values (3, 26, 20);
insert into public.results (student_id, course_id, result) values (50, 12, 18);
insert into public.results (student_id, course_id, result) values (9, 47, 5);
insert into public.results (student_id, course_id, result) values (71, 15, 14);
insert into public.results (student_id, course_id, result) values (39, 8, 15);
insert into public.results (student_id, course_id, result) values (44, 5, 8);
insert into public.results (student_id, course_id, result) values (63, 22, 12);
insert into public.results (student_id, course_id, result) values (68, 18, 5);
insert into public.results (student_id, course_id, result) values (23, 10, 18);
insert into public.results (student_id, course_id, result) values (49, 4, 9);
insert into public.results (student_id, course_id, result) values (7, 34, 14);
insert into public.results (student_id, course_id, result) values (69, 20, 5);
insert into public.results (student_id, course_id, result) values (82, 30, 20);
insert into public.results (student_id, course_id, result) values (47, 3, 1);
insert into public.results (student_id, course_id, result) values (66, 21, 7);
insert into public.results (student_id, course_id, result) values (95, 46, 15);
insert into public.results (student_id, course_id, result) values (35, 23, 11);
insert into public.results (student_id, course_id, result) values (32, 33, 9);
insert into public.results (student_id, course_id, result) values (32, 22, 13);
insert into public.results (student_id, course_id, result) values (56, 26, 7);
insert into public.results (student_id, course_id, result) values (67, 45, 10);
insert into public.results (student_id, course_id, result) values (77, 26, 1);
insert into public.results (student_id, course_id, result) values (52, 36, 5);
insert into public.results (student_id, course_id, result) values (77, 13, 2);
insert into public.results (student_id, course_id, result) values (23, 28, 8);
insert into public.results (student_id, course_id, result) values (5, 46, 6);
insert into public.results (student_id, course_id, result) values (78, 41, 17);
insert into public.results (student_id, course_id, result) values (17, 24, 11);
insert into public.results (student_id, course_id, result) values (44, 36, 9);
insert into public.results (student_id, course_id, result) values (11, 25, 11);
insert into public.results (student_id, course_id, result) values (87, 4, 14);
insert into public.results (student_id, course_id, result) values (52, 36, 12);
insert into public.results (student_id, course_id, result) values (7, 32, 14);
insert into public.results (student_id, course_id, result) values (2, 11, 12);
insert into public.results (student_id, course_id, result) values (85, 33, 3);
insert into public.results (student_id, course_id, result) values (80, 22, 18);
insert into public.results (student_id, course_id, result) values (24, 42, 11);
insert into public.results (student_id, course_id, result) values (2, 38, 14);
insert into public.results (student_id, course_id, result) values (87, 29, 1);
insert into public.results (student_id, course_id, result) values (94, 41, 2);
insert into public.results (student_id, course_id, result) values (12, 41, 9);
insert into public.results (student_id, course_id, result) values (1, 47, 6);
insert into public.results (student_id, course_id, result) values (42, 42, 6);
insert into public.results (student_id, course_id, result) values (98, 27, 5);
insert into public.results (student_id, course_id, result) values (13, 10, 18);
insert into public.results (student_id, course_id, result) values (43, 47, 8);
insert into public.results (student_id, course_id, result) values (9, 2, 10);
insert into public.results (student_id, course_id, result) values (27, 6, 8);
insert into public.results (student_id, course_id, result) values (81, 1, 11);
insert into public.results (student_id, course_id, result) values (2, 42, 17);
insert into public.results (student_id, course_id, result) values (6, 13, 2);
insert into public.results (student_id, course_id, result) values (84, 5, 17);
insert into public.results (student_id, course_id, result) values (95, 42, 4);
insert into public.results (student_id, course_id, result) values (56, 33, 3);
insert into public.results (student_id, course_id, result) values (9, 46, 13);
insert into public.results (student_id, course_id, result) values (72, 36, 11);
insert into public.results (student_id, course_id, result) values (72, 24, 5);
insert into public.results (student_id, course_id, result) values (35, 33, 20);
insert into public.results (student_id, course_id, result) values (67, 16, 10);
insert into public.results (student_id, course_id, result) values (84, 13, 18);
insert into public.results (student_id, course_id, result) values (20, 40, 2);
insert into public.results (student_id, course_id, result) values (7, 7, 19);
insert into public.results (student_id, course_id, result) values (37, 17, 14);
insert into public.results (student_id, course_id, result) values (86, 29, 4);
insert into public.results (student_id, course_id, result) values (46, 23, 7);
insert into public.results (student_id, course_id, result) values (45, 42, 6);
insert into public.results (student_id, course_id, result) values (40, 3, 6);
insert into public.results (student_id, course_id, result) values (79, 7, 3);
insert into public.results (student_id, course_id, result) values (44, 49, 1);
insert into public.results (student_id, course_id, result) values (67, 6, 5);
insert into public.results (student_id, course_id, result) values (13, 7, 18);
insert into public.results (student_id, course_id, result) values (2, 5, 12);
insert into public.results (student_id, course_id, result) values (35, 36, 9);
insert into public.results (student_id, course_id, result) values (63, 12, 18);
insert into public.results (student_id, course_id, result) values (18, 23, 10);
insert into public.results (student_id, course_id, result) values (7, 50, 13);
insert into public.results (student_id, course_id, result) values (78, 16, 14);
insert into public.results (student_id, course_id, result) values (82, 5, 17);
insert into public.results (student_id, course_id, result) values (63, 28, 18);
insert into public.results (student_id, course_id, result) values (20, 9, 12);
insert into public.results (student_id, course_id, result) values (77, 9, 7);
insert into public.results (student_id, course_id, result) values (70, 41, 12);
insert into public.results (student_id, course_id, result) values (19, 6, 5);
insert into public.results (student_id, course_id, result) values (71, 19, 4);
insert into public.results (student_id, course_id, result) values (60, 14, 9);
insert into public.results (student_id, course_id, result) values (42, 25, 12);
insert into public.results (student_id, course_id, result) values (30, 15, 16);
insert into public.results (student_id, course_id, result) values (67, 7, 11);
insert into public.results (student_id, course_id, result) values (36, 10, 1);
insert into public.results (student_id, course_id, result) values (81, 14, 8);
insert into public.results (student_id, course_id, result) values (80, 26, 9);
insert into public.results (student_id, course_id, result) values (64, 32, 20);
insert into public.results (student_id, course_id, result) values (14, 48, 17);
insert into public.results (student_id, course_id, result) values (62, 50, 3);
insert into public.results (student_id, course_id, result) values (39, 25, 14);
insert into public.results (student_id, course_id, result) values (12, 50, 9);
insert into public.results (student_id, course_id, result) values (13, 21, 15);
insert into public.results (student_id, course_id, result) values (3, 14, 19);
insert into public.results (student_id, course_id, result) values (21, 30, 7);
insert into public.results (student_id, course_id, result) values (29, 28, 2);
insert into public.results (student_id, course_id, result) values (86, 42, 11);
insert into public.results (student_id, course_id, result) values (40, 46, 16);
insert into public.results (student_id, course_id, result) values (89, 47, 13);
insert into public.results (student_id, course_id, result) values (88, 32, 3);
insert into public.results (student_id, course_id, result) values (95, 43, 9);
insert into public.results (student_id, course_id, result) values (13, 32, 1);
insert into public.results (student_id, course_id, result) values (20, 9, 19);
insert into public.results (student_id, course_id, result) values (85, 10, 6);
insert into public.results (student_id, course_id, result) values (85, 11, 5);
insert into public.results (student_id, course_id, result) values (95, 40, 12);
insert into public.results (student_id, course_id, result) values (26, 23, 14);
insert into public.results (student_id, course_id, result) values (33, 20, 3);
insert into public.results (student_id, course_id, result) values (76, 10, 13);
insert into public.results (student_id, course_id, result) values (60, 19, 12);
insert into public.results (student_id, course_id, result) values (63, 47, 14);
insert into public.results (student_id, course_id, result) values (83, 18, 11);
insert into public.results (student_id, course_id, result) values (45, 30, 14);
insert into public.results (student_id, course_id, result) values (9, 20, 14);
insert into public.results (student_id, course_id, result) values (20, 16, 4);
insert into public.results (student_id, course_id, result) values (71, 19, 3);
insert into public.results (student_id, course_id, result) values (54, 42, 19);
insert into public.results (student_id, course_id, result) values (48, 18, 13);
insert into public.results (student_id, course_id, result) values (6, 28, 19);
insert into public.results (student_id, course_id, result) values (55, 29, 17);
insert into public.results (student_id, course_id, result) values (67, 26, 7);
insert into public.results (student_id, course_id, result) values (29, 34, 19);
insert into public.results (student_id, course_id, result) values (64, 5, 14);
insert into public.results (student_id, course_id, result) values (1, 48, 19);
insert into public.results (student_id, course_id, result) values (75, 29, 2);
insert into public.results (student_id, course_id, result) values (51, 16, 13);
insert into public.results (student_id, course_id, result) values (51, 37, 20);
insert into public.results (student_id, course_id, result) values (35, 23, 8);
insert into public.results (student_id, course_id, result) values (17, 1, 19);
insert into public.results (student_id, course_id, result) values (86, 28, 12);
insert into public.results (student_id, course_id, result) values (87, 34, 8);
insert into public.results (student_id, course_id, result) values (96, 33, 16);
insert into public.results (student_id, course_id, result) values (42, 38, 18);
insert into public.results (student_id, course_id, result) values (91, 18, 9);
insert into public.results (student_id, course_id, result) values (73, 44, 8);
insert into public.results (student_id, course_id, result) values (72, 34, 12);
insert into public.results (student_id, course_id, result) values (13, 45, 15);
insert into public.results (student_id, course_id, result) values (32, 31, 7);
insert into public.results (student_id, course_id, result) values (34, 3, 16);
insert into public.results (student_id, course_id, result) values (38, 31, 1);
insert into public.results (student_id, course_id, result) values (29, 15, 15);
insert into public.results (student_id, course_id, result) values (68, 6, 8);
insert into public.results (student_id, course_id, result) values (79, 23, 14);
insert into public.results (student_id, course_id, result) values (85, 48, 17);
insert into public.results (student_id, course_id, result) values (87, 26, 2);
insert into public.results (student_id, course_id, result) values (29, 39, 8);
insert into public.results (student_id, course_id, result) values (80, 28, 1);
insert into public.results (student_id, course_id, result) values (36, 27, 5);
insert into public.results (student_id, course_id, result) values (13, 8, 9);
insert into public.results (student_id, course_id, result) values (83, 8, 19);
insert into public.results (student_id, course_id, result) values (86, 18, 13);
insert into public.results (student_id, course_id, result) values (63, 41, 2);
insert into public.results (student_id, course_id, result) values (48, 46, 7);
insert into public.results (student_id, course_id, result) values (68, 5, 1);
insert into public.results (student_id, course_id, result) values (49, 32, 18);
insert into public.results (student_id, course_id, result) values (44, 32, 17);
insert into public.results (student_id, course_id, result) values (66, 23, 16);
insert into public.results (student_id, course_id, result) values (98, 38, 5);
insert into public.results (student_id, course_id, result) values (95, 40, 4);
insert into public.results (student_id, course_id, result) values (51, 37, 2);
insert into public.results (student_id, course_id, result) values (56, 49, 7);
insert into public.results (student_id, course_id, result) values (69, 6, 19);
insert into public.results (student_id, course_id, result) values (26, 13, 17);
insert into public.results (student_id, course_id, result) values (50, 35, 19);
insert into public.results (student_id, course_id, result) values (40, 29, 8);
insert into public.results (student_id, course_id, result) values (60, 6, 11);
insert into public.results (student_id, course_id, result) values (13, 21, 2);
insert into public.results (student_id, course_id, result) values (20, 28, 10);
insert into public.results (student_id, course_id, result) values (19, 49, 20);
insert into public.results (student_id, course_id, result) values (61, 39, 3);
insert into public.results (student_id, course_id, result) values (45, 3, 15);
insert into public.results (student_id, course_id, result) values (48, 42, 18);
insert into public.results (student_id, course_id, result) values (81, 40, 4);
insert into public.results (student_id, course_id, result) values (76, 19, 18);
insert into public.results (student_id, course_id, result) values (45, 17, 2);
insert into public.results (student_id, course_id, result) values (87, 8, 19);
insert into public.results (student_id, course_id, result) values (84, 15, 15);
insert into public.results (student_id, course_id, result) values (37, 18, 11);
insert into public.results (student_id, course_id, result) values (65, 32, 19);
insert into public.results (student_id, course_id, result) values (3, 16, 4);
insert into public.results (student_id, course_id, result) values (17, 25, 16);
insert into public.results (student_id, course_id, result) values (90, 49, 3);
insert into public.results (student_id, course_id, result) values (71, 25, 8);
insert into public.results (student_id, course_id, result) values (26, 44, 15);
insert into public.results (student_id, course_id, result) values (78, 31, 4);
insert into public.results (student_id, course_id, result) values (2, 45, 20);
insert into public.results (student_id, course_id, result) values (4, 6, 12);
insert into public.results (student_id, course_id, result) values (100, 39, 2);
insert into public.results (student_id, course_id, result) values (30, 12, 19);
insert into public.results (student_id, course_id, result) values (72, 7, 13);
insert into public.results (student_id, course_id, result) values (29, 41, 7);
insert into public.results (student_id, course_id, result) values (6, 45, 18);
insert into public.results (student_id, course_id, result) values (17, 9, 4);
insert into public.results (student_id, course_id, result) values (96, 31, 12);
insert into public.results (student_id, course_id, result) values (12, 1, 16);
insert into public.results (student_id, course_id, result) values (25, 22, 4);
insert into public.results (student_id, course_id, result) values (18, 43, 16);
insert into public.results (student_id, course_id, result) values (52, 25, 3);
insert into public.results (student_id, course_id, result) values (17, 26, 2);
insert into public.results (student_id, course_id, result) values (25, 15, 20);
insert into public.results (student_id, course_id, result) values (81, 6, 20);
insert into public.results (student_id, course_id, result) values (20, 36, 9);
insert into public.results (student_id, course_id, result) values (84, 14, 6);
insert into public.results (student_id, course_id, result) values (55, 48, 8);
insert into public.results (student_id, course_id, result) values (44, 34, 15);
insert into public.results (student_id, course_id, result) values (32, 19, 15);
insert into public.results (student_id, course_id, result) values (11, 8, 11);
insert into public.results (student_id, course_id, result) values (43, 28, 17);
insert into public.results (student_id, course_id, result) values (8, 49, 1);
insert into public.results (student_id, course_id, result) values (76, 22, 12);
insert into public.results (student_id, course_id, result) values (87, 6, 2);
insert into public.results (student_id, course_id, result) values (37, 41, 5);
insert into public.results (student_id, course_id, result) values (88, 29, 18);
insert into public.results (student_id, course_id, result) values (21, 33, 17);
insert into public.results (student_id, course_id, result) values (45, 24, 8);
insert into public.results (student_id, course_id, result) values (36, 17, 15);
insert into public.results (student_id, course_id, result) values (97, 32, 17);
insert into public.results (student_id, course_id, result) values (80, 21, 5);
insert into public.results (student_id, course_id, result) values (2, 26, 7);
insert into public.results (student_id, course_id, result) values (84, 33, 10);
insert into public.results (student_id, course_id, result) values (34, 14, 5);
insert into public.results (student_id, course_id, result) values (57, 42, 17);
insert into public.results (student_id, course_id, result) values (32, 20, 8);
insert into public.results (student_id, course_id, result) values (56, 9, 6);
insert into public.results (student_id, course_id, result) values (75, 50, 3);
insert into public.results (student_id, course_id, result) values (33, 11, 18);
insert into public.results (student_id, course_id, result) values (84, 31, 14);
insert into public.results (student_id, course_id, result) values (19, 44, 2);
insert into public.results (student_id, course_id, result) values (14, 48, 7);
insert into public.results (student_id, course_id, result) values (85, 33, 5);
insert into public.results (student_id, course_id, result) values (41, 43, 17);
insert into public.results (student_id, course_id, result) values (74, 28, 6);
insert into public.results (student_id, course_id, result) values (55, 33, 11);
insert into public.results (student_id, course_id, result) values (32, 17, 17);
insert into public.results (student_id, course_id, result) values (96, 45, 4);
insert into public.results (student_id, course_id, result) values (32, 37, 1);
insert into public.results (student_id, course_id, result) values (25, 11, 3);
insert into public.results (student_id, course_id, result) values (65, 22, 3);
insert into public.results (student_id, course_id, result) values (85, 13, 2);
insert into public.results (student_id, course_id, result) values (39, 31, 20);
insert into public.results (student_id, course_id, result) values (2, 50, 2);
insert into public.results (student_id, course_id, result) values (45, 8, 11);
insert into public.results (student_id, course_id, result) values (64, 35, 7);
insert into public.results (student_id, course_id, result) values (95, 14, 2);
insert into public.results (student_id, course_id, result) values (5, 20, 14);
insert into public.results (student_id, course_id, result) values (57, 24, 2);
insert into public.results (student_id, course_id, result) values (38, 26, 9);
insert into public.results (student_id, course_id, result) values (25, 26, 7);
insert into public.results (student_id, course_id, result) values (91, 36, 4);
insert into public.results (student_id, course_id, result) values (67, 48, 6);
insert into public.results (student_id, course_id, result) values (84, 2, 20);
insert into public.results (student_id, course_id, result) values (31, 25, 1);
insert into public.results (student_id, course_id, result) values (48, 22, 19);
insert into public.results (student_id, course_id, result) values (98, 30, 14);
insert into public.results (student_id, course_id, result) values (95, 34, 2);
insert into public.results (student_id, course_id, result) values (92, 31, 2);
insert into public.results (student_id, course_id, result) values (38, 35, 3);
insert into public.results (student_id, course_id, result) values (25, 30, 14);
insert into public.results (student_id, course_id, result) values (3, 11, 8);
insert into public.results (student_id, course_id, result) values (66, 34, 19);
insert into public.results (student_id, course_id, result) values (61, 23, 13);
insert into public.results (student_id, course_id, result) values (24, 40, 19);
insert into public.results (student_id, course_id, result) values (32, 17, 12);
insert into public.results (student_id, course_id, result) values (78, 5, 1);
insert into public.results (student_id, course_id, result) values (82, 11, 16);
insert into public.results (student_id, course_id, result) values (74, 8, 13);
insert into public.results (student_id, course_id, result) values (48, 42, 18);
insert into public.results (student_id, course_id, result) values (6, 48, 20);
insert into public.results (student_id, course_id, result) values (96, 46, 11);
insert into public.results (student_id, course_id, result) values (54, 46, 3);
insert into public.results (student_id, course_id, result) values (98, 7, 18);
insert into public.results (student_id, course_id, result) values (36, 42, 20);
insert into public.results (student_id, course_id, result) values (99, 24, 13);
insert into public.results (student_id, course_id, result) values (75, 7, 8);
insert into public.results (student_id, course_id, result) values (68, 20, 14);
insert into public.results (student_id, course_id, result) values (82, 6, 13);
insert into public.results (student_id, course_id, result) values (35, 45, 9);
insert into public.results (student_id, course_id, result) values (39, 19, 13);
insert into public.results (student_id, course_id, result) values (95, 9, 16);
insert into public.results (student_id, course_id, result) values (100, 46, 7);
insert into public.results (student_id, course_id, result) values (86, 28, 11);
insert into public.results (student_id, course_id, result) values (90, 47, 7);
insert into public.results (student_id, course_id, result) values (9, 39, 3);
insert into public.results (student_id, course_id, result) values (2, 31, 11);
insert into public.results (student_id, course_id, result) values (7, 49, 10);
insert into public.results (student_id, course_id, result) values (42, 11, 9);
insert into public.results (student_id, course_id, result) values (9, 38, 17);
insert into public.results (student_id, course_id, result) values (50, 50, 19);
insert into public.results (student_id, course_id, result) values (100, 44, 13);
insert into public.results (student_id, course_id, result) values (84, 48, 1);
insert into public.results (student_id, course_id, result) values (26, 39, 15);
insert into public.results (student_id, course_id, result) values (80, 33, 15);
insert into public.results (student_id, course_id, result) values (54, 31, 4);
insert into public.results (student_id, course_id, result) values (40, 6, 6);
insert into public.results (student_id, course_id, result) values (88, 49, 12);
insert into public.results (student_id, course_id, result) values (1, 21, 6);
insert into public.results (student_id, course_id, result) values (58, 22, 14);
insert into public.results (student_id, course_id, result) values (93, 1, 6);
insert into public.results (student_id, course_id, result) values (70, 49, 15);
insert into public.results (student_id, course_id, result) values (71, 33, 1);
insert into public.results (student_id, course_id, result) values (73, 9, 12);
insert into public.results (student_id, course_id, result) values (2, 13, 17);
insert into public.results (student_id, course_id, result) values (61, 17, 2);
insert into public.results (student_id, course_id, result) values (59, 29, 12);
insert into public.results (student_id, course_id, result) values (68, 47, 10);
insert into public.results (student_id, course_id, result) values (92, 8, 12);
insert into public.results (student_id, course_id, result) values (61, 28, 10);
insert into public.results (student_id, course_id, result) values (1, 20, 9);
insert into public.results (student_id, course_id, result) values (95, 42, 3);
insert into public.results (student_id, course_id, result) values (17, 41, 10);
insert into public.results (student_id, course_id, result) values (12, 10, 15);
insert into public.results (student_id, course_id, result) values (17, 6, 9);
insert into public.results (student_id, course_id, result) values (44, 33, 15);
insert into public.results (student_id, course_id, result) values (10, 35, 4);
insert into public.results (student_id, course_id, result) values (31, 19, 4);
insert into public.results (student_id, course_id, result) values (44, 4, 3);
insert into public.results (student_id, course_id, result) values (37, 27, 12);
insert into public.results (student_id, course_id, result) values (24, 29, 15);
insert into public.results (student_id, course_id, result) values (52, 45, 3);
insert into public.results (student_id, course_id, result) values (22, 33, 3);
insert into public.results (student_id, course_id, result) values (83, 25, 4);
insert into public.results (student_id, course_id, result) values (80, 42, 2);
insert into public.results (student_id, course_id, result) values (1, 43, 4);
insert into public.results (student_id, course_id, result) values (91, 13, 10);
insert into public.results (student_id, course_id, result) values (98, 5, 20);
insert into public.results (student_id, course_id, result) values (45, 4, 16);
insert into public.results (student_id, course_id, result) values (2, 17, 12);
insert into public.results (student_id, course_id, result) values (39, 40, 17);
insert into public.results (student_id, course_id, result) values (12, 18, 9);
insert into public.results (student_id, course_id, result) values (94, 7, 20);
insert into public.results (student_id, course_id, result) values (61, 13, 13);
insert into public.results (student_id, course_id, result) values (70, 17, 7);
insert into public.results (student_id, course_id, result) values (18, 46, 5);
insert into public.results (student_id, course_id, result) values (47, 8, 10);
insert into public.results (student_id, course_id, result) values (78, 7, 9);
insert into public.results (student_id, course_id, result) values (14, 15, 14);
insert into public.results (student_id, course_id, result) values (61, 7, 8);
insert into public.results (student_id, course_id, result) values (46, 46, 7);
insert into public.results (student_id, course_id, result) values (35, 18, 10);
insert into public.results (student_id, course_id, result) values (84, 7, 11);
insert into public.results (student_id, course_id, result) values (87, 37, 14);
insert into public.results (student_id, course_id, result) values (79, 1, 4);
insert into public.results (student_id, course_id, result) values (71, 10, 20);
insert into public.results (student_id, course_id, result) values (70, 38, 19);
insert into public.results (student_id, course_id, result) values (70, 23, 20);
insert into public.results (student_id, course_id, result) values (39, 40, 3);
insert into public.results (student_id, course_id, result) values (73, 17, 17);
insert into public.results (student_id, course_id, result) values (64, 4, 1);
insert into public.results (student_id, course_id, result) values (55, 28, 12);
insert into public.results (student_id, course_id, result) values (18, 38, 9);
insert into public.results (student_id, course_id, result) values (64, 22, 15);
insert into public.results (student_id, course_id, result) values (79, 15, 16);
insert into public.results (student_id, course_id, result) values (21, 12, 11);
insert into public.results (student_id, course_id, result) values (76, 22, 19);
insert into public.results (student_id, course_id, result) values (48, 24, 9);
insert into public.results (student_id, course_id, result) values (4, 3, 12);
insert into public.results (student_id, course_id, result) values (88, 32, 13);
insert into public.results (student_id, course_id, result) values (97, 48, 11);
insert into public.results (student_id, course_id, result) values (39, 50, 5);
insert into public.results (student_id, course_id, result) values (79, 18, 16);
insert into public.results (student_id, course_id, result) values (17, 13, 7);
insert into public.results (student_id, course_id, result) values (32, 14, 13);
insert into public.results (student_id, course_id, result) values (64, 46, 19);
insert into public.results (student_id, course_id, result) values (63, 2, 8);
insert into public.results (student_id, course_id, result) values (15, 34, 1);
insert into public.results (student_id, course_id, result) values (61, 32, 5);
insert into public.results (student_id, course_id, result) values (74, 18, 5);
insert into public.results (student_id, course_id, result) values (62, 7, 11);
insert into public.results (student_id, course_id, result) values (64, 19, 11);
insert into public.results (student_id, course_id, result) values (15, 17, 6);
insert into public.results (student_id, course_id, result) values (42, 41, 1);
insert into public.results (student_id, course_id, result) values (77, 4, 1);
insert into public.results (student_id, course_id, result) values (15, 5, 1);
insert into public.results (student_id, course_id, result) values (68, 29, 16);
insert into public.results (student_id, course_id, result) values (1, 27, 15);
insert into public.results (student_id, course_id, result) values (11, 34, 5);
insert into public.results (student_id, course_id, result) values (68, 15, 6);
insert into public.results (student_id, course_id, result) values (88, 10, 14);
insert into public.results (student_id, course_id, result) values (11, 29, 12);
insert into public.results (student_id, course_id, result) values (26, 32, 6);
insert into public.results (student_id, course_id, result) values (51, 3, 1);
insert into public.results (student_id, course_id, result) values (8, 4, 12);
insert into public.results (student_id, course_id, result) values (72, 24, 14);
insert into public.results (student_id, course_id, result) values (50, 15, 12);
insert into public.results (student_id, course_id, result) values (26, 27, 18);
insert into public.results (student_id, course_id, result) values (11, 23, 6);
insert into public.results (student_id, course_id, result) values (99, 45, 10);
insert into public.results (student_id, course_id, result) values (34, 28, 20);
insert into public.results (student_id, course_id, result) values (65, 42, 2);
insert into public.results (student_id, course_id, result) values (78, 7, 20);
insert into public.results (student_id, course_id, result) values (59, 41, 12);
insert into public.results (student_id, course_id, result) values (7, 3, 16);
insert into public.results (student_id, course_id, result) values (58, 24, 10);
insert into public.results (student_id, course_id, result) values (45, 20, 9);
insert into public.results (student_id, course_id, result) values (63, 10, 13);
insert into public.results (student_id, course_id, result) values (54, 24, 7);
insert into public.results (student_id, course_id, result) values (36, 3, 20);
insert into public.results (student_id, course_id, result) values (88, 44, 4);
insert into public.results (student_id, course_id, result) values (85, 46, 7);
insert into public.results (student_id, course_id, result) values (77, 10, 15);
insert into public.results (student_id, course_id, result) values (2, 32, 11);
insert into public.results (student_id, course_id, result) values (33, 32, 7);
insert into public.results (student_id, course_id, result) values (58, 2, 3);
insert into public.results (student_id, course_id, result) values (20, 28, 7);
insert into public.results (student_id, course_id, result) values (42, 14, 14);
insert into public.results (student_id, course_id, result) values (1, 42, 14);
insert into public.results (student_id, course_id, result) values (40, 27, 10);
insert into public.results (student_id, course_id, result) values (36, 50, 20);
insert into public.results (student_id, course_id, result) values (55, 9, 3);
insert into public.results (student_id, course_id, result) values (31, 36, 18);
insert into public.results (student_id, course_id, result) values (91, 4, 7);
insert into public.results (student_id, course_id, result) values (72, 49, 4);
insert into public.results (student_id, course_id, result) values (86, 44, 5);
insert into public.results (student_id, course_id, result) values (69, 9, 6);
insert into public.results (student_id, course_id, result) values (28, 20, 18);
insert into public.results (student_id, course_id, result) values (62, 9, 3);
insert into public.results (student_id, course_id, result) values (9, 39, 1);
insert into public.results (student_id, course_id, result) values (92, 35, 6);
insert into public.results (student_id, course_id, result) values (80, 5, 14);
insert into public.results (student_id, course_id, result) values (34, 31, 6);
insert into public.results (student_id, course_id, result) values (42, 31, 11);
insert into public.results (student_id, course_id, result) values (87, 26, 13);
insert into public.results (student_id, course_id, result) values (9, 2, 8);
insert into public.results (student_id, course_id, result) values (66, 28, 2);
insert into public.results (student_id, course_id, result) values (44, 34, 14);
insert into public.results (student_id, course_id, result) values (47, 13, 17);
insert into public.results (student_id, course_id, result) values (43, 24, 3);
insert into public.results (student_id, course_id, result) values (63, 39, 3);
insert into public.results (student_id, course_id, result) values (3, 11, 12);
insert into public.results (student_id, course_id, result) values (5, 15, 14);
insert into public.results (student_id, course_id, result) values (20, 42, 2);
insert into public.results (student_id, course_id, result) values (43, 24, 4);
insert into public.results (student_id, course_id, result) values (26, 44, 18);
insert into public.results (student_id, course_id, result) values (73, 18, 17);
insert into public.results (student_id, course_id, result) values (36, 29, 12);
insert into public.results (student_id, course_id, result) values (82, 33, 1);
insert into public.results (student_id, course_id, result) values (100, 14, 15);
insert into public.results (student_id, course_id, result) values (43, 20, 20);
insert into public.results (student_id, course_id, result) values (5, 2, 14);
insert into public.results (student_id, course_id, result) values (48, 36, 7);
insert into public.results (student_id, course_id, result) values (61, 6, 10);
insert into public.results (student_id, course_id, result) values (84, 20, 4);
insert into public.results (student_id, course_id, result) values (99, 49, 9);
insert into public.results (student_id, course_id, result) values (65, 39, 11);
insert into public.results (student_id, course_id, result) values (54, 44, 6);
insert into public.results (student_id, course_id, result) values (63, 11, 20);
insert into public.results (student_id, course_id, result) values (56, 44, 4);
insert into public.results (student_id, course_id, result) values (25, 40, 20);
insert into public.results (student_id, course_id, result) values (20, 2, 12);
insert into public.results (student_id, course_id, result) values (42, 6, 18);
insert into public.results (student_id, course_id, result) values (8, 14, 20);
insert into public.results (student_id, course_id, result) values (34, 39, 4);
insert into public.results (student_id, course_id, result) values (87, 17, 12);
insert into public.results (student_id, course_id, result) values (63, 23, 11);
insert into public.results (student_id, course_id, result) values (34, 34, 7);
insert into public.results (student_id, course_id, result) values (36, 17, 10);
insert into public.results (student_id, course_id, result) values (94, 2, 3);
insert into public.results (student_id, course_id, result) values (81, 49, 8);
insert into public.results (student_id, course_id, result) values (100, 32, 17);
insert into public.results (student_id, course_id, result) values (63, 47, 6);
insert into public.results (student_id, course_id, result) values (88, 46, 12);
insert into public.results (student_id, course_id, result) values (41, 45, 9);
insert into public.results (student_id, course_id, result) values (68, 48, 9);
insert into public.results (student_id, course_id, result) values (81, 50, 13);
insert into public.results (student_id, course_id, result) values (59, 40, 1);
insert into public.results (student_id, course_id, result) values (46, 3, 15);
insert into public.results (student_id, course_id, result) values (83, 48, 17);
insert into public.results (student_id, course_id, result) values (99, 24, 13);
insert into public.results (student_id, course_id, result) values (39, 47, 19);
insert into public.results (student_id, course_id, result) values (66, 4, 13);
insert into public.results (student_id, course_id, result) values (42, 21, 3);
insert into public.results (student_id, course_id, result) values (53, 45, 14);
insert into public.results (student_id, course_id, result) values (20, 27, 8);
insert into public.results (student_id, course_id, result) values (81, 35, 13);
insert into public.results (student_id, course_id, result) values (8, 17, 13);
insert into public.results (student_id, course_id, result) values (25, 14, 13);
insert into public.results (student_id, course_id, result) values (53, 37, 13);
insert into public.results (student_id, course_id, result) values (56, 40, 8);
insert into public.results (student_id, course_id, result) values (33, 44, 6);
insert into public.results (student_id, course_id, result) values (18, 36, 6);
insert into public.results (student_id, course_id, result) values (83, 35, 4);
insert into public.results (student_id, course_id, result) values (51, 2, 20);
insert into public.results (student_id, course_id, result) values (66, 49, 8);
insert into public.results (student_id, course_id, result) values (21, 9, 12);
insert into public.results (student_id, course_id, result) values (74, 14, 11);
insert into public.results (student_id, course_id, result) values (63, 10, 7);
insert into public.results (student_id, course_id, result) values (69, 50, 16);
insert into public.results (student_id, course_id, result) values (59, 14, 16);
insert into public.results (student_id, course_id, result) values (72, 24, 14);
insert into public.results (student_id, course_id, result) values (48, 16, 6);
insert into public.results (student_id, course_id, result) values (97, 49, 14);
insert into public.results (student_id, course_id, result) values (26, 49, 2);
insert into public.results (student_id, course_id, result) values (83, 6, 1);
insert into public.results (student_id, course_id, result) values (23, 10, 16);
insert into public.results (student_id, course_id, result) values (45, 5, 7);
insert into public.results (student_id, course_id, result) values (87, 13, 2);
insert into public.results (student_id, course_id, result) values (90, 37, 9);
insert into public.results (student_id, course_id, result) values (75, 33, 5);
insert into public.results (student_id, course_id, result) values (96, 7, 5);
insert into public.results (student_id, course_id, result) values (56, 25, 10);
insert into public.results (student_id, course_id, result) values (61, 28, 3);
insert into public.results (student_id, course_id, result) values (99, 2, 3);
insert into public.results (student_id, course_id, result) values (51, 34, 3);
insert into public.results (student_id, course_id, result) values (22, 41, 12);
insert into public.results (student_id, course_id, result) values (41, 10, 13);
insert into public.results (student_id, course_id, result) values (13, 23, 11);
insert into public.results (student_id, course_id, result) values (34, 34, 14);
insert into public.results (student_id, course_id, result) values (89, 41, 15);
insert into public.results (student_id, course_id, result) values (16, 16, 14);
insert into public.results (student_id, course_id, result) values (89, 29, 6);
insert into public.results (student_id, course_id, result) values (78, 50, 7);
insert into public.results (student_id, course_id, result) values (43, 50, 4);
insert into public.results (student_id, course_id, result) values (15, 47, 6);
insert into public.results (student_id, course_id, result) values (48, 27, 5);
insert into public.results (student_id, course_id, result) values (94, 37, 11);
insert into public.results (student_id, course_id, result) values (5, 4, 20);
insert into public.results (student_id, course_id, result) values (74, 32, 20);
insert into public.results (student_id, course_id, result) values (22, 46, 13);
insert into public.results (student_id, course_id, result) values (10, 37, 1);
insert into public.results (student_id, course_id, result) values (60, 5, 8);
insert into public.results (student_id, course_id, result) values (13, 18, 6);
insert into public.results (student_id, course_id, result) values (21, 19, 4);
insert into public.results (student_id, course_id, result) values (80, 18, 3);
insert into public.results (student_id, course_id, result) values (36, 6, 8);
insert into public.results (student_id, course_id, result) values (13, 48, 20);
insert into public.results (student_id, course_id, result) values (95, 32, 9);
insert into public.results (student_id, course_id, result) values (46, 2, 6);
insert into public.results (student_id, course_id, result) values (50, 22, 3);
insert into public.results (student_id, course_id, result) values (17, 25, 15);
insert into public.results (student_id, course_id, result) values (72, 10, 1);
insert into public.results (student_id, course_id, result) values (69, 23, 5);
insert into public.results (student_id, course_id, result) values (1, 44, 7);
insert into public.results (student_id, course_id, result) values (77, 20, 20);
insert into public.results (student_id, course_id, result) values (91, 35, 10);
insert into public.results (student_id, course_id, result) values (56, 50, 10);
insert into public.results (student_id, course_id, result) values (62, 7, 2);
insert into public.results (student_id, course_id, result) values (75, 25, 20);
insert into public.results (student_id, course_id, result) values (15, 50, 7);
insert into public.results (student_id, course_id, result) values (82, 35, 3);
insert into public.results (student_id, course_id, result) values (59, 21, 5);
insert into public.results (student_id, course_id, result) values (16, 9, 9);
insert into public.results (student_id, course_id, result) values (85, 49, 12);
insert into public.results (student_id, course_id, result) values (14, 34, 9);
insert into public.results (student_id, course_id, result) values (59, 50, 17);
insert into public.results (student_id, course_id, result) values (27, 35, 16);
insert into public.results (student_id, course_id, result) values (53, 34, 3);
insert into public.results (student_id, course_id, result) values (61, 10, 19);
insert into public.results (student_id, course_id, result) values (91, 19, 8);
insert into public.results (student_id, course_id, result) values (38, 2, 5);
insert into public.results (student_id, course_id, result) values (14, 46, 14);
insert into public.results (student_id, course_id, result) values (35, 37, 10);
insert into public.results (student_id, course_id, result) values (38, 34, 18);
insert into public.results (student_id, course_id, result) values (69, 20, 18);
insert into public.results (student_id, course_id, result) values (44, 2, 11);
insert into public.results (student_id, course_id, result) values (33, 1, 19);
insert into public.results (student_id, course_id, result) values (52, 30, 15);
insert into public.results (student_id, course_id, result) values (56, 31, 15);
insert into public.results (student_id, course_id, result) values (47, 38, 7);
insert into public.results (student_id, course_id, result) values (82, 34, 9);
insert into public.results (student_id, course_id, result) values (45, 1, 19);
insert into public.results (student_id, course_id, result) values (74, 45, 6);
insert into public.results (student_id, course_id, result) values (21, 8, 3);
insert into public.results (student_id, course_id, result) values (86, 20, 19);
insert into public.results (student_id, course_id, result) values (25, 29, 18);
insert into public.results (student_id, course_id, result) values (19, 43, 18);
insert into public.results (student_id, course_id, result) values (55, 46, 10);
insert into public.results (student_id, course_id, result) values (16, 3, 7);
insert into public.results (student_id, course_id, result) values (30, 4, 19);
insert into public.results (student_id, course_id, result) values (43, 36, 17);
insert into public.results (student_id, course_id, result) values (64, 20, 18);
insert into public.results (student_id, course_id, result) values (81, 38, 4);
insert into public.results (student_id, course_id, result) values (77, 2, 14);
insert into public.results (student_id, course_id, result) values (45, 17, 17);
insert into public.results (student_id, course_id, result) values (76, 11, 13);
insert into public.results (student_id, course_id, result) values (83, 40, 18);
insert into public.results (student_id, course_id, result) values (71, 24, 6);
insert into public.results (student_id, course_id, result) values (58, 50, 4);
insert into public.results (student_id, course_id, result) values (30, 17, 8);
insert into public.results (student_id, course_id, result) values (50, 16, 13);
insert into public.results (student_id, course_id, result) values (91, 29, 19);
insert into public.results (student_id, course_id, result) values (80, 23, 14);
insert into public.results (student_id, course_id, result) values (28, 50, 19);
insert into public.results (student_id, course_id, result) values (49, 4, 19);
insert into public.results (student_id, course_id, result) values (67, 2, 9);
insert into public.results (student_id, course_id, result) values (30, 28, 5);
insert into public.results (student_id, course_id, result) values (40, 3, 4);
insert into public.results (student_id, course_id, result) values (97, 45, 5);
insert into public.results (student_id, course_id, result) values (52, 17, 8);
insert into public.results (student_id, course_id, result) values (88, 27, 14);
insert into public.results (student_id, course_id, result) values (96, 28, 10);
insert into public.results (student_id, course_id, result) values (59, 27, 15);
insert into public.results (student_id, course_id, result) values (61, 24, 6);
insert into public.results (student_id, course_id, result) values (80, 14, 6);
insert into public.results (student_id, course_id, result) values (58, 22, 11);
insert into public.results (student_id, course_id, result) values (51, 7, 11);
insert into public.results (student_id, course_id, result) values (97, 30, 9);
insert into public.results (student_id, course_id, result) values (41, 17, 4);
insert into public.results (student_id, course_id, result) values (20, 34, 7);
insert into public.results (student_id, course_id, result) values (50, 47, 11);
insert into public.results (student_id, course_id, result) values (89, 32, 14);
insert into public.results (student_id, course_id, result) values (67, 50, 12);
insert into public.results (student_id, course_id, result) values (92, 12, 8);
insert into public.results (student_id, course_id, result) values (62, 9, 3);
insert into public.results (student_id, course_id, result) values (15, 13, 20);
insert into public.results (student_id, course_id, result) values (37, 9, 12);
insert into public.results (student_id, course_id, result) values (17, 43, 7);
insert into public.results (student_id, course_id, result) values (78, 22, 11);
insert into public.results (student_id, course_id, result) values (96, 15, 1);
insert into public.results (student_id, course_id, result) values (44, 36, 13);
insert into public.results (student_id, course_id, result) values (29, 18, 20);
insert into public.results (student_id, course_id, result) values (38, 16, 20);
insert into public.results (student_id, course_id, result) values (13, 3, 18);
insert into public.results (student_id, course_id, result) values (24, 45, 6);
insert into public.results (student_id, course_id, result) values (57, 46, 2);
insert into public.results (student_id, course_id, result) values (47, 18, 4);
insert into public.results (student_id, course_id, result) values (58, 4, 15);
insert into public.results (student_id, course_id, result) values (37, 16, 11);
insert into public.results (student_id, course_id, result) values (55, 19, 17);
insert into public.results (student_id, course_id, result) values (71, 20, 3);
insert into public.results (student_id, course_id, result) values (52, 27, 17);
insert into public.results (student_id, course_id, result) values (75, 18, 4);
insert into public.results (student_id, course_id, result) values (33, 24, 17);
insert into public.results (student_id, course_id, result) values (67, 8, 6);
insert into public.results (student_id, course_id, result) values (95, 42, 16);
insert into public.results (student_id, course_id, result) values (64, 50, 13);
insert into public.results (student_id, course_id, result) values (10, 1, 16);
insert into public.results (student_id, course_id, result) values (52, 30, 6);
insert into public.results (student_id, course_id, result) values (67, 2, 4);
insert into public.results (student_id, course_id, result) values (60, 38, 1);
insert into public.results (student_id, course_id, result) values (95, 48, 17);
insert into public.results (student_id, course_id, result) values (78, 31, 11);
insert into public.results (student_id, course_id, result) values (83, 30, 10);
insert into public.results (student_id, course_id, result) values (46, 14, 9);
insert into public.results (student_id, course_id, result) values (78, 20, 15);
insert into public.results (student_id, course_id, result) values (53, 5, 7);
insert into public.results (student_id, course_id, result) values (35, 9, 6);
insert into public.results (student_id, course_id, result) values (70, 8, 3);
insert into public.results (student_id, course_id, result) values (59, 21, 15);
insert into public.results (student_id, course_id, result) values (75, 24, 4);
insert into public.results (student_id, course_id, result) values (73, 20, 15);
insert into public.results (student_id, course_id, result) values (17, 29, 9);
insert into public.results (student_id, course_id, result) values (83, 39, 15);
insert into public.results (student_id, course_id, result) values (20, 27, 5);
insert into public.results (student_id, course_id, result) values (18, 27, 8);
insert into public.results (student_id, course_id, result) values (17, 8, 14);
insert into public.results (student_id, course_id, result) values (25, 6, 7);
insert into public.results (student_id, course_id, result) values (36, 23, 15);
insert into public.results (student_id, course_id, result) values (68, 33, 14);
insert into public.results (student_id, course_id, result) values (49, 16, 7);
insert into public.results (student_id, course_id, result) values (67, 34, 3);
insert into public.results (student_id, course_id, result) values (99, 20, 10);
insert into public.results (student_id, course_id, result) values (100, 25, 17);
insert into public.results (student_id, course_id, result) values (3, 4, 4);
insert into public.results (student_id, course_id, result) values (65, 10, 16);
insert into public.results (student_id, course_id, result) values (62, 10, 7);
insert into public.results (student_id, course_id, result) values (27, 36, 20);
insert into public.results (student_id, course_id, result) values (36, 27, 17);
insert into public.results (student_id, course_id, result) values (41, 10, 9);
insert into public.results (student_id, course_id, result) values (72, 3, 12);
insert into public.results (student_id, course_id, result) values (17, 45, 17);
insert into public.results (student_id, course_id, result) values (10, 46, 14);
insert into public.results (student_id, course_id, result) values (11, 19, 14);
insert into public.results (student_id, course_id, result) values (49, 45, 2);
insert into public.results (student_id, course_id, result) values (36, 44, 3);
insert into public.results (student_id, course_id, result) values (91, 4, 20);
insert into public.results (student_id, course_id, result) values (71, 37, 18);
insert into public.results (student_id, course_id, result) values (23, 33, 17);
insert into public.results (student_id, course_id, result) values (97, 22, 6);
insert into public.results (student_id, course_id, result) values (56, 43, 15);
insert into public.results (student_id, course_id, result) values (65, 10, 15);
insert into public.results (student_id, course_id, result) values (36, 36, 1);
